//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapClient.HotelSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8080", ConfigurationName="HotelSoap.HotelsPort")]
    public interface HotelsPort {
        
        // CODEGEN: Generating message contract since the operation getName is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapClient.HotelSoap.getNameResponse1 getName(SoapClient.HotelSoap.getNameRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapClient.HotelSoap.getNameResponse1> getNameAsync(SoapClient.HotelSoap.getNameRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://localhost:8080")]
    public partial class getNameRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://localhost:8080")]
    public partial class getNameResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNameRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080", Order=0)]
        public SoapClient.HotelSoap.getNameRequest getNameRequest;
        
        public getNameRequest1() {
        }
        
        public getNameRequest1(SoapClient.HotelSoap.getNameRequest getNameRequest) {
            this.getNameRequest = getNameRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNameResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080", Order=0)]
        public SoapClient.HotelSoap.getNameResponse getNameResponse;
        
        public getNameResponse1() {
        }
        
        public getNameResponse1(SoapClient.HotelSoap.getNameResponse getNameResponse) {
            this.getNameResponse = getNameResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HotelsPortChannel : SoapClient.HotelSoap.HotelsPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelsPortClient : System.ServiceModel.ClientBase<SoapClient.HotelSoap.HotelsPort>, SoapClient.HotelSoap.HotelsPort {
        
        public HotelsPortClient() {
        }
        
        public HotelsPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelsPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelsPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelsPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapClient.HotelSoap.getNameResponse1 SoapClient.HotelSoap.HotelsPort.getName(SoapClient.HotelSoap.getNameRequest1 request) {
            return base.Channel.getName(request);
        }
        
        public SoapClient.HotelSoap.getNameResponse getName(SoapClient.HotelSoap.getNameRequest getNameRequest) {
            SoapClient.HotelSoap.getNameRequest1 inValue = new SoapClient.HotelSoap.getNameRequest1();
            inValue.getNameRequest = getNameRequest;
            SoapClient.HotelSoap.getNameResponse1 retVal = ((SoapClient.HotelSoap.HotelsPort)(this)).getName(inValue);
            return retVal.getNameResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapClient.HotelSoap.getNameResponse1> SoapClient.HotelSoap.HotelsPort.getNameAsync(SoapClient.HotelSoap.getNameRequest1 request) {
            return base.Channel.getNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapClient.HotelSoap.getNameResponse1> getNameAsync(SoapClient.HotelSoap.getNameRequest getNameRequest) {
            SoapClient.HotelSoap.getNameRequest1 inValue = new SoapClient.HotelSoap.getNameRequest1();
            inValue.getNameRequest = getNameRequest;
            return ((SoapClient.HotelSoap.HotelsPort)(this)).getNameAsync(inValue);
        }
    }
}
